SHELL=/bin/bash

test:
	nosetests --with-coverage --cover-package=../ ANN_simulation_test.py   # nosetests with coverage

clean:
	rm -rf *.pkl *.pyc *.png *.txt *.pdb *.pdf *.hdf5 *.chk bck.* NDATA temp_save *.npy temp_model.dot temp_save_pytorch .coverage *.pth

