SHELL=/bin/bash

test:
	nosetests --with-coverage --cover-package=current_work ANN_simulation_test.py   # nosetests with coverage

clean:
	rm -rf *.pkl *.pyc *.png *.txt *.pdb *.pdf *.hdf5 *.chk bck.* NDATA temp_save *.npy

